/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import koneksi.Koneksi;

/**
 *
 * @author user
 */
public class FormPopupBarang extends javax.swing.JFrame {
    private FormNota parent;
    private DefaultTableModel model;
    /**
     * Creates new form FormPopupBarang
     */
    public FormPopupBarang(FormNota parent) {
        this.parent = parent;
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        // Setup tabel model
        model = new DefaultTableModel();
        model.addColumn("KD Barang");
        model.addColumn("Nama");
        model.addColumn("Harga Beli");
        model.addColumn("Harga Jual");
        model.addColumn("QTY");
        model.addColumn("Total");
        TblBg.setModel(model);

        // load data
        loadData("");
        

        // Event klik pada tabel
        TblBg.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int row = TblBg.getSelectedRow();
                String kode = model.getValueAt(row, 0).toString();
                String nama = model.getValueAt(row, 1).toString();
                int hargaBeli = Integer.parseInt(model.getValueAt(row, 2).toString());
                int hargaJual = Integer.parseInt(model.getValueAt(row, 3).toString());

                String qtyStr = JOptionPane.showInputDialog("Masukkan jumlah (QTY):");
                if (qtyStr != null && !qtyStr.isEmpty()) {
                    try {
                        int qty = Integer.parseInt(qtyStr);
                        int total = qty * hargaJual;

                        parent.setBarang(kode, nama, hargaBeli, hargaJual, qty, total);
                        dispose();
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(null, "Input QTY tidak valid!");
                    }
                }
            }
        });

        // Tombol cari (dummy)
        btnCariPopupbg.addActionListener(e -> {
            String keyword = txtPopupbg.getText();
            loadData(keyword);
        });
    }
    private void loadData(String keyword) {
    model.setRowCount(0); // reset tabel
    try {
        Connection conn = Koneksi.getKoneksi();
        String sql = "SELECT * FROM barang WHERE nama_barang LIKE ? OR kode_barang LIKE ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        String key = "%" + keyword + "%";
        pst.setString(1, key);
        pst.setString(2, key);
        ResultSet rs = pst.executeQuery();
        while (rs.next()) {
            String kode = rs.getString("kode_barang");
            String nama = rs.getString("nama_barang");
            int hBeli = rs.getInt("harga_beli");
            int hJual = rs.getInt("harga_jual");
            model.addRow(new Object[]{kode, nama, hBeli, hJual, 0, 0});
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Gagal mengambil data: " + ex.getMessage());
    }
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPopupbg = new javax.swing.JTextField();
        btnCariPopupbg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblBg = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCariPopupbg.setText("Cari");
        btnCariPopupbg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariPopupbgActionPerformed(evt);
            }
        });

        TblBg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "KD Barang", "Nama", "Harga Beli", "Harga Jual", "QTY", "Total"
            }
        ));
        jScrollPane1.setViewportView(TblBg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPopupbg, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCariPopupbg, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPopupbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariPopupbg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariPopupbgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariPopupbgActionPerformed
        String keyword = txtPopupbg.getText();
        loadData(keyword);
    }//GEN-LAST:event_btnCariPopupbgActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblBg;
    private javax.swing.JButton btnCariPopupbg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPopupbg;
    // End of variables declaration//GEN-END:variables
}
