/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.sql.*;
import koneksi.Koneksi;

/**
 *
 * @author user
 */
public class FormPopupPelanggan extends javax.swing.JFrame {
    private FormNota parent;
    private DefaultTableModel model;

    /**
     * Creates new form FromPopupPelanggan
     */
    public FormPopupPelanggan(FormNota parent) {
        this.parent = parent;
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        model = new DefaultTableModel(
            new String[]{"Id Pelanggan", "Nama", "Alamat"}, 0
        );
        tablepopup.setModel(model);
        loadData("");

        tablepopup.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int row = tablepopup.getSelectedRow();
                String id = model.getValueAt(row, 0).toString();
                String nama = model.getValueAt(row, 1).toString();
                String alamat = model.getValueAt(row, 2).toString();

                if (parent != null) {
                    parent.setPelanggan(id, nama, alamat);
                }
                dispose();
            }
        });

        // Event tombol cari
        btnCaripopup.addActionListener(e -> {
            String keyword = txtCaripopup.getText();
            loadData(keyword);
        });
    }

    private void loadData(String keyword) {
        model.setRowCount(0); // bersihkan tabel
        try {
            Connection conn = koneksi.Koneksi.getKoneksi();
            String sql = "SELECT * FROM pelanggan WHERE id_pelanggan LIKE ? OR nama_pelanggan LIKE ? OR alamat LIKE ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            String key = "%" + keyword + "%";
            ps.setString(1, key);
            ps.setString(2, key);
            ps.setString(3, key);

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_pelanggan"),
                    rs.getString("nama_pelanggan"),
                    rs.getString("alamat")
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + ex.getMessage());
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCaripopup = new javax.swing.JTextField();
        btnCaripopup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablepopup = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCaripopup.setText("Cari");
        btnCaripopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaripopupActionPerformed(evt);
            }
        });

        tablepopup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Pelanggan", "Nama", "Alamat"
            }
        ));
        jScrollPane1.setViewportView(tablepopup);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCaripopup, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCaripopup, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 158, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCaripopup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCaripopup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaripopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaripopupActionPerformed
        String keyword = txtCaripopup.getText();
            loadData(keyword);
    }//GEN-LAST:event_btnCaripopupActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaripopup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablepopup;
    private javax.swing.JTextField txtCaripopup;
    // End of variables declaration//GEN-END:variables
}
